<div class="container">
	<div class="row py-5 px-5">
		<form class="col" method="post" action="/pessoa/salvar" id="adicionarCandidato">
			<fieldset><legend class="h2">Dados pessoais</legend>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="nome">Nome</label>
							<input type="text" value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['nome'])) ? Core\Utilitarios\Sessoes::loadForm()['nome']: '' ?>" name="nome" id="nome"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="sobrenome">Sobresobrenome</label>
							<input type="text" value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['sobrenome'])) ? Core\Utilitarios\Sessoes::loadForm()['sobrenome']: '' ?>" name="sobrenome" id="sobrenome"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="cpf">Cpf / Cnpj</label>
							<input type="text"  value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['cpf_cnpj'])) ? Core\Utilitarios\Sessoes::loadForm()['cpf_cnpj']: '' ?>" name="cpf_cnpj"id="cpf" class="form-control form-control-sm" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="sexo">Sexo</label>
							<select name="sexo" id="sexo"class="form-control form-control-sm" required="required">
								<option <?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['sexo']) && Core\Utilitarios\Sessoes::loadForm()['sexo'] =='m' ) ? 'selected': '' ?> value="m">Masculino</option>

								<option  <?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['sexo']) && Core\Utilitarios\Sessoes::loadForm()['sexo'] =='f' ) ? 'selected': '' ?> value="f">Feminino</option>
							</select>
						</div>
						<div class="form-group">
							<label for="email">E-mail</label>
							<input type="email" value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['email'])) ? Core\Utilitarios\Sessoes::loadForm()['email']: '' ?>" name="email" id="email"class="form-control form-control-sm" required="required">
						</div>
						<div class="row">
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<label for="phone_1" required="required">Telefone 1</label>
									<input type="tel" value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['phone_1'])) ? Core\Utilitarios\Sessoes::loadForm()['phone_1']: '' ?>" name="phone_1" id="phone_1" class="form-control form-control-sm" required="required">
								</div>
							</div>
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<label for="phone_2">Telefone 2</label>
									<input type="tel" value="<?= ((Core\Utilitarios\Sessoes::loadForm() != false) && isset(Core\Utilitarios\Sessoes::loadForm()['phone_2'])) ? Core\Utilitarios\Sessoes::loadForm()['phone_2']: '' ?>" name="phone_2" id="phone_2" class="form-control form-control-sm">
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row my-3">
					<div class="col" align="left">
						<span class="h2 mr-2">Endereço</span>
						<button type="button" class="btn btn-primary mb-2" id="adicionar-logradouro">
							<i class="fas fa-plus-circle fa-1x"></i>
						</button>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col" align="left">
						<div class="table-responsive">
							<table class="table table-md table-sm table-hover" id="table-logradouro">
				              <thead>
				                <tr>
				                  <th>Estado</th>
				                  <th>Cidade</th>
				                  <th>Bairro</th>
				                  <th>Logradouro</th>
				                  <th>Complemento</th>
				                  <th>Tipo</th>
				                  <th>Numero</th>
				                  <th>Ação</th>
				                </tr>
				              </thead>  
				              <tbody>
				              </tbody>  
				            </table>
				        </div>
					</div>
				</div>
			</fieldset>				
			<button class="btn btn-success mb-2" type="submit">Cadastrar</button>
			<a class="btn btn-danger mb-2" href="/" >Cancelar</a>
		</form>
	</div>
</div>