<div class="container">
	<div class="row px-5" style="float: right;">
		<nav class="navbar navbar-expand-lg">
			<ul class="navbar-nav mr-auto" >
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/" id="">Inicio</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/pessoa/index" id="">Lista de pessoas</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>" id="">Painel da pessoa</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-primary" id="">Editar pessoa</a>
				</li>
			</ul>
		</nav>
	</div>
	<div class="row mb-2 px-5" style="clear: both;">
		<div class="col" align="left">
			<h2>Titular:  <?= ucwords($this->view->dados[0]->getNome(). ' '.$this->view->dados[0]->getSobrenome())?></h2>	
		</div>
	</div>
	<div class="row pb-5 px-5" >
		<nav class="navbar navbar-expand-lg bg-info" style="width: 100%; align-items: center;">
			<div class="" id="">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item mr-1">
				        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Pessoais</a>
				    </li>
				    <li class="nav-item mr-1">
				        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="/logradouro/index?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Logradouro</a>
				    </li>
				</ul>
			</div>
		</nav>
	</div>
	<div class="row py-5 px-5">
		 <form class="col" method="post" action="/pessoa/atualizar" id="adicionarCandidato">
			<fieldset><legend class="h2">Dados pessoais</legend>
				<input type="hidden" name="pessoa" value="<?= $this->view->dados[0]->getIdPessoa(); ?>">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="nome">Nome</label>
							<input type="text" value="<?= $this->view->dados[0]->getNome(); ?>" name="nome" id="nome"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="sobrenome">Sobresobrenome</label>
							<input type="text" value="<?=$this->view->dados[0]->getSobrenome(); ?>" name="sobrenome" id="sobrenome"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="cpf">Cpf / Cnpj</label>
							<input type="text"  value="<?= $this->view->dados[0]->getCpfCnpj(); ?>" name="cpf_cnpj"id="cpf" class="form-control form-control-sm" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="sexo">Sexo</label>
							<select name="sexo" id="sexo"class="form-control form-control-sm" required="required">
								<option <?= ($this->view->dados[0]->getSexo() =='m' ) ? 'selected': '' ?> value="m">Masculino</option>

								<option  <?= ($this->view->dados[0]->getSexo() =='f' ) ? 'selected': '' ?> value="f">Feminino</option>
							</select>
						</div>
						<div class="form-group">
							<label for="email">E-mail</label>
							<input type="email" value="<?=  $this->view->dados[0]->getEmail(); ?>" name="email" id="email"class="form-control form-control-sm" required="required">
						</div>
						<div class="row">
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<label for="phone_1" required="required">Telefone 1</label>
									<input type="tel" value="" name="phone_1" id="phone_1" class="form-control form-control-sm" required="required">
								</div>
							</div>
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<label for="phone_2">Telefone 2</label>
									<input type="tel" value="" name="phone_2" id="phone_2" class="form-control form-control-sm">
								</div>
							</div>
						</div>
					</div>
				</div>
            <button class="btn btn-sm  mr-2 mb-2 btn-outline-success" type="submit">Adicionar</button>
            <a class="btn btn-sm  mr-2 mb-2 btn-outline-danger" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>" >Cancelar</a>
          <fieldset>
        </form>
	</div>
</div>