<div class="row py-5 px-5">
	<div class="col-md-12 px-4 col-sm-12  mb-2">
		<div class="row">
			<div style="" class="col p-4 mb-2 mr-2 rounded border bg-white col-shadow" align="center">
				<h2 class="mb-3">Lista de pessoas</h2>

				<div class="row">
					<div class="col" align="right">
						<a href="/pessoa/adicionar" class="btn btn-secondary mb-2" id="adicionar-pessoa">
							<i class="fas fa-plus-circle fa-1x"></i>
						</a>
					</div>
				</div>
				<?php


					if((! isset($this->view->dados)) || ($this->view->dados == false)){

				?>

					<div class="row">
						<div class="col alert alert-warning" align="center">Nenhum registro encontrado!</div>
					</div>
				
				<?php

					}else{
				?>	
					<div class="table-responsive">
						<table class="table table-md table-sm table-hover">
							<thead>
								<tr>
									<th>Nome</th>
									<th>Sobrenome</th>
									<th>Cpf</th>
									<th>E-mail</th>
									<th>Ação</th>
								</tr>
							</thead>	
							<tbody>
								<?php 
									for($i = 0; !($i == count($this->view->dados)); $i++){
								?>
								<tr>
									<td><?=$this->view->dados[$i]->getNome();?></td>
									<td><?=$this->view->dados[$i]->getSobrenome();?></td>
									<td><?=$this->view->dados[$i]->getCpfCnpj();?></td>
									<td><?=$this->view->dados[$i]->getEmail();?></td>
									<td>
										<a class="btn btn-sm btn-primary" href="/pessoa/visualizar?cd=<?=$this->view->dados[$i]->getIdPessoa();?>"><i class="fas fa-search-plus"></i></a>
										<a class="btn btn-sm btn-success" href="/pessoa/editar?cd=<?=$this->view->dados[$i]->getIdPessoa();?>"><i class="fas fa-pencil-alt"></i></a>
										<a class="btn btn-sm btn-danger" href="/pessoa/visualizar?cd=<?=$this->view->dados[$i]->getIdPessoa();?>"><i class="fas fa-trash-alt"></i></a>
									</td>
								</tr>
								<?php

									}
								 ?>
							</tbody>	
						</table>
					</div>
				<?php 

					}

				?>
			</div>
	</div>
</div>
