<div class="container" style="width: 50%; margin: auto;">
	<div class="row mt-5" align="center">
		<div class="col pb-5 px-5"><h2>Deletar Registro?</h2></div>
	</div>
	<div class="row pb-5 px-5" align="center" >
		<div class="col-md-6 p-3 col-sm-12" align="left">
			<p class="h2">Pessoa</p>
			<p align="left"><strong>Nome: </strong><?=$this->view->dados[0]->getNome();?></p>
			<p align="left"><strong>Sobrenome: </strong><?=$this->view->dados[0]->getSobrenome();?></p>
			<p align="left"><strong>CPF: </strong><?=$this->view->dados[0]->getCpfCnpj();?></p>
			<p align="left"><strong>Sexo: </strong><?=$this->view->dados[0]->getSexo() == 'f' ? 'Feminino' : 'Masculino';?></p>
		</div>
		<div class="col-md-6 p-3 col-sm-12" align="left">
			<p class="h2">Enderço</p>
			<?php 
				$logradPess = $this->view->dados[0]->pessoaLogradouro();

          		if($logradPess != false){
					for($i = 0; !($i == count($logradPess)); $i++){
			?>
			
				<p><strong>Estado: </strong><?=$logradPess[$i]->logradouro()[0]->getEndereco();?></p>
				<p><strong>Cidade: </strong><?=$logradPess[$i]->logradouro()[0]->getCidade();?></p>
				<p><strong>Bairro: </strong><?=$logradPess[$i]->logradouro()[0]->getBairro();?></p>
				<p><strong>Logrdouro: </strong><?=$logradPess[$i]->logradouro()[0]->getEndereco();?></p>
				<p><strong>Complemento: </strong><?=$logradPess[$i]->logradouro()[0]->getComplemento();?></p>
				<p><strong>Tipo: </strong><?=$logradPess[$i]->logradouro()[0]->getTipo();?></p>
				<p><strong>Número: </strong><?=$logradPess[$i]->logradouro()[0]->getNumero();?></p>
				<hr/>
			
			<?php

					}
				}
			 ?>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<p align="center"><a href="#" class="btn btn-md mr-2 mb-2 btn-outline-danger">Deletar</a><a href="/pessoa/index" class="btn btn-md mb-2 btn-outline-primary">Cancelar</a>
			</p>
		</div>
	</div>
</div>