<div class="row px-5" style="float: right;">
	<nav class="navbar navbar-expand-lg">
		<ul class="navbar-nav mr-auto" >
			<li class="nav-item mr-1 ">
				<a class="nav-link link-option alert alert-white" href="/" id="">Inicio</a>
			</li>
			<li class="nav-item mr-1 ">
				<a class="nav-link link-option alert alert-white" href="/pessoa/index" id="">Lista de pessoas</a>
			</li>
			<li class="nav-item mr-1 ">
				<a class="nav-link link-option alert alert-primary" id="">Painel da pessoa</a>
			</li>
		</ul>
	</nav>
</div>
<div class="row mb-2 px-5" style="clear: both;">
	<div class="col" align="left">
		<h2>Titular:  <?= ucwords($this->view->dados[0]->getNome(). ' '.$this->view->dados[0]->getSobrenome())?></h2>	
	</div>
</div>
<div class="row mb-5 px-5" style="">
	<nav class="navbar navbar-expand-lg bg-info" style=" width: 100%; height: 100%; align-items: center; margin: auto;">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item mr-1">
		        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Pessoais</a>
		    </li>
		    <li class="nav-item mr-1">
		        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="/logradouro/index?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Logradouro</a>
		    </li>
		</ul>
	</nav>
</div>
<div class="row py-5 px-5">
	<div class="col-md-12 px-4 col-sm-12  mb-2">
		<div class="row">
			<div style="" class="col p-4 mb-2 mr-2 rounded border bg-white col-shadow" align="center">
				<h2 class="mb-3">Info pessoais</h2>
				<?php


					if((! isset($this->view->dados)) || ($this->view->dados == false)){

				?>

					<div class="row">
						<div class="col alert alert-warning" align="center">Nenhum registro encontrado!</div>
					</div>
				
				<?php

					}else{
				?>	
						<div class="row" style="width: 50%; margin: auto;">
							<div class="col p-4">
								<p align="left"><strong>Nome: </strong><?=$this->view->dados[0]->getNome();?></p>
								<p align="left"><strong>Sobrenome: </strong><?=$this->view->dados[0]->getSobrenome();?></p>
								<p align="left"><strong>CPF: </strong><?=$this->view->dados[0]->getCpfCnpj();?></p>
								<p align="left"><strong>Sexo: </strong><?=$this->view->dados[0]->getSexo() == 'f' ? 'Feminino' : 'Masculino';?></p>
							</div>
						</div>
						<div class="row"style="width: 50%; margin: auto;">
							<div class="col p-4">
								<a class="btn btn-sm btn-success" href="/pessoa/editar?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Editar</a>
										<a class="btn btn-sm btn-danger" href="/pessoa/info?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Excluir</a>
							</div>
						</div>
				<?php 

					}

				?>
			</div>
	</div>
</div>
