
<nav class="navbar navbar-expand-lg navbar-light alert-primary" id="nav-menu">
	<div class="container">
	  <a class="navbar-brand" href="/">Admin</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	    	<li class="nav-item active mr-1 dropdown">
	    		<a class="nav-link dropdown-toggle desable-link" href="#" id="minha-area" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Minha area
	        </a>
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="minha-area">
	          <a class="dropdown-item" href="/usuario/index">Sair</a>
	        </div>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle desable-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Pessoa
	        </a>
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item link-option desable-link" href="/pessoa/adicionar">Adicionar</a>
	          <a class="dropdown-item link-option desable-link" href="/pessoa/index">Lista</a>	          
	        </div>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle desable-link" href="#" id="recibo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Recibo
	        </a>
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="recibo">
	          <a class="dropdown-item link-option desable-link" href="#">Novo</a>  
	        </div>
	      </li>
	    </ul>
	  </div>
  </div>
</nav>