<div class="row px-5" style="float: right;">
	<nav class="navbar navbar-expand-lg">
		<ul class="navbar-nav mr-auto" >
			<li class="nav-item mr-1 ">
				<a class="nav-link link-option alert alert-primary" id="pessoal">Inicio</a>
			</li>
		</ul>
	</nav>
</div>
<div class="row py-3 px-5" id="painel-index-admin" style="clear: both;">
	<div class="col">
		<div class="row mb-2" style="height: auto;">
			<div class="col bg-info" >
				<h4 style="">Financeiro</h4>
			</div>
		</div>
		<div class="row mb-2">
			<div class="col-sm-3 mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Contas a receber</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Contas a pagar</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Lançar despesa</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Lançar receita</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Comparativos</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Gerar recibo</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row mb-2" style="height: auto;">
			<div class="col bg-info">
				<h4 style="">Vendas</h4>
			</div>
		</div>
		<div class="row mb-2">
			<div class="col-sm-3 mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Clientes</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo cliente</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Pedidos</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo pedido</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row mb-2" style="height: auto;">
			<div class="col  bg-info">
				<h4 style="">Estoque</h4>
			</div>
		</div>
		<div class="row mb-2">
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Podutos</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo produto</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Estoque</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3  mb-2">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo estoque</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3 ">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Transferir estoque</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row mb-2" style="height: auto;">
			<div class="col bg-info">
				<h4 style="">Recursos humanos</h4>
			</div>
		</div>
		<div class="row mb-2">
			<div class="col-sm-3 ">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Usuarios</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3 ">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/pessoa/index" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-users fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo usuario</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3 ">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Funiconarios</span>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-sm-3 ">
				<div class="row">
					<div class="col-sm-12" align="center">
						<a href="/recibo" class="row">
							<div class="col-sm-4">
								<span><i class="fas fa-file-invoice fa-3x"></i></span>
							</div>
							<div class="col-sm-8" align="left">
								<span>Novo funcionario</span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</div>