<div class="row px-5" style="float: right;">
	<nav class="navbar navbar-expand-lg">
		<ul class="navbar-nav mr-auto" >
			<li class="nav-item mr-1 ">
				<a class="nav-link link-option alert alert-primary" id="pessoal">Inicio</a>
			</li>
		</ul>
	</nav>
</div>
<div class="row py-5 px-5" id="painel-index-admin" style="clear: both;">
	<div class="col mx-2">
		<div class="row">
			<a href="/pessoa/index">
				<div class="col-sm-12 px-4 py-4 col-md-5" align="center">
					<h2>Clientes:</h2>
					<span><i class="fas fa-users fa-5x"></i></span>
				</div>
			</a>
		</div>
	</div>
	<div class="col mx-2">
		<div class="row">
			<a href="#">
				<div class="col-sm-12 px-4 py-4 col-md-5" align="center">
					<h2>Recibo:</h2>
					<span><i class="fas fa-file-invoice fa-5x"></i></span>
				</div>
			</a>
		</div>
	</div>
</div>