<div class="row">
	<div class="col" align="" style="height: 700px;">
		<form class="form py-5 px-5" method="post" action="/usuario/logar" style="" id="login">
			<fieldset><legend  align="center" class="h1"><center>Login</center></legend>
				<div class="form-group py-1 mb-3 bg-primary" style="border-radius: 50%; width: 60%; margin: auto;"></div>
				<div class="form-group">
					<label for="usuario">Usuario:</label>
					<input required="required" id="usuario" type="email" name="usuario" class="form-control form-control-sm">
				</div>
				<div class="form-group">
					<label for="senha">Senha:</label>
					<input required="required" id="senha" type="password" name="senha" class="form-control form-control-sm">
				</div>
				<div class="form-group" style="display: flex; justify-content: space-between;">
					<button class="btn btn-xs btn-primary" style="">Entrar</button>
				</div>
			</fieldset>
		</form>
	</div>
</div>