<div class="container">
	<div class="row px-5" style="float: right;">
		<nav class="navbar navbar-expand-lg">
			<ul class="navbar-nav mr-auto" >
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/" id="">Inicio</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/pessoa/index" id="">Lista de pessoas</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-white" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>" id="">Painel da pessoa</a>
				</li>
				<li class="nav-item mr-1 ">
					<a class="nav-link link-option alert alert-primary" id="">Excluir logradouro</a>
				</li>
			</ul>
		</nav>
	</div>
</div>
<div class="row mb-2 px-5" style="clear: both;">
	<div class="col" align="left">
		<h2>Titular:  <?=$this->view->dados[0]->pessoa()[0]->getNome(). ' '.$this->view->dados[0]->pessoa()[0]->getSobrenome();?></h2>	
	</div>
</div>
<div class="row mb-5 px-5">
	<nav class="navbar navbar-expand-lg bg-info" style="width: 100%; align-items: center;">
		<div class="" id="">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item mr-1">
			        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/pessoa/painel?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Pessoais</a>
			    </li>
			    <li class="nav-item mr-1">
			        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="/logradouro/index?cd=<?=$this->view->dados[0]->getIdPessoa();?>">Logradouro</a>
			    </li>
			</ul>
		</div>
	</nav>
</div>
<div class="container" style="width: 50%; margin: auto;">
	<div class="row mt-5" align="center">
		<div class="col px-5 alert alert-warning" align="center"><h4 class="">Deseja realmente Deletar este Registro?</h4></div>
	</div>
		<div class="col-md-12 p-3 col-sm-12" align="left">
			<p class="h2">Enderço</p>
			<?php 
				$logradPess = $this->view->dados;

          		if($logradPess != false){
					for($i = 0; !($i == count($logradPess)); $i++){
			?>
			
				<p><strong>Estado: </strong><?=$logradPess[$i]->logradouro()[0]->getEndereco();?></p>
				<p><strong>Cidade: </strong><?=$logradPess[$i]->logradouro()[0]->getCidade();?></p>
				<p><strong>Bairro: </strong><?=$logradPess[$i]->logradouro()[0]->getBairro();?></p>
				<p><strong>Logrdouro: </strong><?=$logradPess[$i]->logradouro()[0]->getEndereco();?></p>
				<p><strong>Complemento: </strong><?=$logradPess[$i]->logradouro()[0]->getComplemento();?></p>
				<p><strong>Tipo: </strong><?=$logradPess[$i]->logradouro()[0]->getTipo();?></p>
				<p><strong>Número: </strong><?=$logradPess[$i]->logradouro()[0]->getNumero();?></p>
				<hr/>
			
			<?php

					}
				}else{

			 ?>
			 	<p class="alert alert-warning">Nenhum endereço cadastrado!</p>
			 	<p class="" align="center"><a href="#" class="btn btn-sm  mr-2 mb-2 btn-outline-primary">Adicionar endereço</a></p>
			 <?php

				}
			 ?>
		</div>
	</div>
	<div class="row">
		<div class="col pb-5 px-5">
			<p align="center"><a href="/logradouro/deletar?cd=<?=$this->view->dados[0]->getIdLogradouro().'&ps='.$this->view->dados[0]->getIdPessoa();?>" class="btn btn-sm  mr-2 mb-2 btn-outline-danger">Deletar</a><a href="/logradouro/index?cd=<?=$this->view->dados[0]->getIdPessoa();?>" class="btn btn-sm mb-2 btn-outline-primary">Cancelar</a>
			</p>
		</div>
	</div>
</div>